<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Abacus.Run.Core/Abacus.Run.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="$(MicrosoftExtensionsVersion)" />
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" Version="10.7.0" />
  </ItemGroup>
</Project>
