// <auto-generated />
using System;
using Abacus.Run.Service.Infrastructure.Auditing;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Abacus.Run.Service.Infrastructure.Auditing.Migrations
{
    [DbContext(typeof(AuditRecordDbContext))]
    [Migration("20260809164853_InitialAuditRecords")]
    partial class InitialAuditRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Abacus.Run.Service.Infrastructure.Auditing.AuditRecordEntryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RecordedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SectionKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId", "SectionKind", "Key")
                        .IsUnique();

                    b.ToTable("AuditRecordEntries");
                });

            modelBuilder.Entity("Abacus.Run.Service.Infrastructure.Auditing.AuditRecordRootRow", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClosedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OpenedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("InstanceId");

                    b.HasIndex("WorkflowName", "RootKey");

                    b.HasIndex("WorkflowName", "Status");

                    b.ToTable("AuditRecords");
                });

            modelBuilder.Entity("Abacus.Run.Service.Infrastructure.Auditing.AuditRecordEntryRow", b =>
                {
                    b.HasOne("Abacus.Run.Service.Infrastructure.Auditing.AuditRecordRootRow", "Root")
                        .WithMany("Entries")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Root");
                });

            modelBuilder.Entity("Abacus.Run.Service.Infrastructure.Auditing.AuditRecordRootRow", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
